name: com.whitelabel.search
description: Search system.
publish_to: "none"
author: com.whitelabel.search
environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bit_set: ^0.1.0
  firebase: ^3.2.0
  sembast: ^1.3.7
  lzma: "^0.3.0"
